/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockAdderRow: typeof import('./src/components/BlockAdderRow.vue')['default']
    BlockRenderer: typeof import('./src/components/BlockRenderer.vue')['default']
    BlockWrapper: typeof import('./src/components/BlockWrapper.vue')['default']
    Button: typeof import('./src/components/blocks/button.vue')['default']
    Columns: typeof import('./src/components/blocks/columns.vue')['default']
    Container: typeof import('./src/components/blocks/container.vue')['default']
    Divider: typeof import('./src/components/blocks/divider.vue')['default']
    Footer: typeof import('./src/components/blocks/footer.vue')['default']
    Hero: typeof import('./src/components/blocks/hero.vue')['default']
    Image: typeof import('./src/components/blocks/image.vue')['default']
    Image_text: typeof import('./src/components/blocks/image_text.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    Inspector: typeof import('./src/components/Inspector.vue')['default']
    LayersPanel: typeof import('./src/components/LayersPanel.vue')['default']
    Product_card: typeof import('./src/components/blocks/product_card.vue')['default']
    Quote: typeof import('./src/components/blocks/quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section_label: typeof import('./src/components/blocks/section_label.vue')['default']
    SendModal: typeof import('./src/components/SendModal.vue')['default']
    Social: typeof import('./src/components/blocks/social.vue')['default']
    Spacer: typeof import('./src/components/blocks/spacer.vue')['default']
    Text: typeof import('./src/components/blocks/text.vue')['default']
    Video_thumb: typeof import('./src/components/blocks/video_thumb.vue')['default']
  }
}
